name: WorkFlow for Linkedin script

on:
  schedule:
    - cron: "30 22 1-31/2 * *"
  workflow_dispatch: # ✅ Add this to allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Scraper/job_portal_extractor

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: execute py script
        run: python old_linkedin.py
